export const FETCH_COMMENTS_FAILED = "FETCH_COMMENTS_FAILED";
export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";

export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";

export const SAVE_CURRENT_SUCCESS = "SAVE_CURRENT_SUCCESS";
